
; [mysql生产]
;mysql_hostname     =172.18.70.251
;mysql_port         = 3306
;mysql_user         = jstxb
;mysql_pass         = JStxb0408@
;mysql_databasename = payflow

; [mysql测试]
;mysql_hostname     =192.168.26.149
;mysql_port         = 3306
;mysql_user         = root
;mysql_pass         = mysql
;mysql_databasename = payflow

; [mysql开发]
mysql_hostname     =192.168.26.149
mysql_port         = 3306
mysql_user         = root
mysql_pass         = mysql
mysql_databasename = payflow

; [mysql本地]
;mysql_hostname     =127.0.0.1
;mysql_port         = 3306
;mysql_user         = root
;mysql_pass         = shx19930509321
;mysql_databasename = payflow

;日志配置
;[logconf]
log_maxAge       = 365 ;//日志最大保存时间（天）
log_rotationTime = 24  ;//日志切割时间间隔（小时）
log_Path         = "./log"
log_FileName     = "etcGasDataCenter.log"

;[redis]
;redis_addr         = "172.18.70.252:6379"
redis_addr         = "192.168.26.248:6379"

;[ip_address]
ip_address          =192.168.26.248:6099

;[frequency]
frequency          =144

;[kafka_ip 生产]
kafka_ipa          ="172.18.70.8:9092"
kafka_ipb          ="172.18.70.17:9092"
kafka_ipc          ="172.18.70.18:9092"
ddkafka_topic      ="billExitDataCollectTopic"


;[kafka_ip 开发]
kafka_ip          ="192.168.26.149:9092"
;单点出口数据收集topic
ddkafka_topic      ="billGasStationDataCollectTopic"


